language: perl

if: tag IS blank

before_script:
  - cpanm MediaWiki::API
  - ls -ld /home/travis/build/SIWECOS/translations/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base
  - cp siwecos.conf.sample siwecos.conf
  - cp wiki.conf.sample wiki.conf

script:
  - time perl ./dir2lang -t build
  - cd build; zip -r ../translation-files.zip *; cd ../

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "$GITHUB_SIWECOSBOT_USERNAME"
  - git config --local user.email "$GITHUB_SIWECOSBOT_EMAIL"
  - git remote add gh https://${GITHUB_SIWECOSBOT_TOKEN}@github.com/siwecos/translations
  # Needed for deploy section
  - export TRAVIS_TAG=latest
  - git tag -f $TRAVIS_TAG
  - git push -f gh $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_SIWECOSBOT_TOKEN
  file: translation-files.zip
  name: 'Translation-Update'
  body: "Translation files update"
  overwrite: true
  skip_cleanup: true
  on:
    branch: v2
