language: perl

before_script:
  - cp siwecos.conf.sample siwecos.conf
  - cp wiki.conf.sample wiki.conf

script:
  - perl ./dir2lang -t build
  - cd build; zip -r ../translation-files.zip *; cd ../

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "$GITHUB_SIWECOSBOT_USERNAME"
  - git config --local user.email "$GITHUB_SIWECOSBOT_EMAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_SIWECOSBOT_TOKEN
  file: translation-files.zip
  skip_cleanup: true
  on:
    branch: travis-build
